version: "3.9"

services:
  myalbum:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./front:/app:cached
      - myalbum_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    tty: true

volumes:
  myalbum_node_modules:
